### ISSUE TITLE
row_spec() background does not work with full_width = TRUE

### ISSUE THREAD

**Issue by sharlagelfand** [haozhu233/kableExtra#372] opened 2019-04-08 18:20 UTC
This seems similar to #363 -- I am not able to set the background color in `row_spec()` when using `full_width = TRUE` and pdf output.

````
---
output: pdf_document
---

```{r}
library(kableExtra)

head(mtcars) %>%
  kable() %>%
  kable_styling(full_width = FALSE) %>%
  row_spec(row = 1,
           color = "white",
           background = "black")
```

```{r}
head(mtcars) %>%
  kable() %>%
  kable_styling(full_width = TRUE) %>%
  row_spec(row = 1,
           color = "white",
           background = "black")
```
````

output of the first:

![](https://i.imgur.com/gW5h1jQ.png)

and the second:

![](https://i.imgur.com/eSyB4vX.png)

Note that actually the color argument works (the font is white!) but the background does not! I don't have this issue with HTML output.

**Comment by haozhu233** [comment] 2019-04-26 21:58
Emm, after some research, I would say this one is actually quite difficult to fix. 

Right now the only good way to color the background of a row in latex is through `colortbl`. In the past, we could still use `xcolor` but this option got removed from table last year because of an update in fancyvbr.
https://github.com/yihui/knitr/issues/1635

Problem with `colortbl` is that it doesn't work with tabu. As suggested in the question below, we should use tabu's own \taburowcolors, which in fact is a wrapper of xcolor...
https://tex.stackexchange.com/questions/36089/bug-in-tabu-when-rowcolors-are-defined

Even in the past, this is quite difficult because `tabu`'s \taburowcolors will apply on every row. In the example above you can see they defined a color for the header row and defined it back to white for all the following rows, which clearly isn't a good choice here for row_spec......

latex can give you surprises everyday. :P

I will close this as there is no good solutions right now...

**Closed** 2019-04-26 21:59 UTC

**Comment by sharlagelfand** [comment] 2019-04-27 17:00
thanks for looking into this @haozhu233! just in case anyone finds this issue looking for help, a workaround i've been doing is manually setting the column widths using `column_spec()` -- that at least allows for a table to manually be made wider, even if it's not an automatic full width.

thanks again!!

**Comment by smmurphy** [comment] 2019-09-11 14:15
Just FYI, I can reproduce this error, but am only seeing this in Windows. Running the same code on Ubuntu 18.04 seems to work fine. Haven't figured out why yet though.
