### ISSUE TITLE
When setting hline_after = TRUE in the row_spec() function for PDF (LaTeX) output, an extra line break is inserted in the LaTeX \midrule.

### ISSUE THREAD

**Issue by ujtwr** [haozhu233/kableExtra#833] opened 2024-04-04 09:43 UTC
This is the reproducible code.

```{r}
library(tidyverse)
library(kableExtra)

tibble(
  V1 = LETTERS[1:5],
  V2 = LETTERS[6:10]
) %>% 
  kbl(
    format = "latex",
    caption = "abc",
    booktabs = TRUE,
  ) %>%
  kable_styling(
    latex_options = c(
      "scale_down",
      "HOLD_position"
    )
  ) %>%
  row_spec(0, align = "c") %>% 
  row_spec(c(1, 3, 4), hline_after = TRUE)
```

The LaTeX source for the result is as follows:

```{latex}
\begin{table}[H]
\centering
\caption{abc}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{ll}
\toprule
\multicolumn{1}{c}{V1} & \multicolumn{1}{c}{V2}\\
\midrule
A & F\\
\midrule\\
B & G\\
C & H\\
\midrule\\
D & I\\
\midrule\\
E & J\\
\bottomrule
\end{tabular}}
\end{table}
```
The "\midrule" outputted by row_spec has a "\\\\" at the end. So, the table of PDF has extra white lines.

![Clipboard 1](https://github.com/haozhu233/kableExtra/assets/42717412/4eb080f7-84f8-45bb-b3ed-21c652438092)

**Comment by ujtwr** [comment] 2024-04-04 09:55
There has been an additional discovery.
It seems that when combined with the "striped" option in kable_stylying(), there are no extra line breaks after rows with colored cells.

```{r}
library(tidyverse)
library(kableExtra)

tibble(
  V1 = LETTERS[1:5],
  V2 = LETTERS[6:10]
) %>% 
  kbl(
    format = "latex",
    caption = "abc",
    booktabs = TRUE,
  ) %>%
  kable_styling(
    latex_options = c(
      "scale_down",
      "striped",
      "HOLD_position"
    )
  ) %>%
  row_spec(0, align = "c") %>% 
  row_spec(c(1, 3, 4), hline_after = TRUE)
```
Latex output is follows:

```{latex}
\begin{table}[H]
\centering
\caption{abc}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{ll}
\toprule
\multicolumn{1}{c}{V1} & \multicolumn{1}{c}{V2}\\
\midrule
\cellcolor{gray!10}{A} & \cellcolor{gray!10}{F}\\
\midrule
B & G\\
\cellcolor{gray!10}{C} & \cellcolor{gray!10}{H}\\
\midrule
D & I\\
\midrule\\
\cellcolor{gray!10}{E} & \cellcolor{gray!10}{J}\\
\bottomrule
\end{tabular}}
\end{table}
```
![Clipboard 1](https://github.com/haozhu233/kableExtra/assets/42717412/2fae977e-4d1e-4281-974a-96851e8d368f)

**Comment by dmurdoch** [comment] 2024-04-11 20:17
This is a duplicate of #815, which has been fixed.

**Closed by dmurdoch** 2024-04-11 20:17 UTC
