### ISSUE TITLE
saving the table as an image

### ISSUE THREAD

**Issue by TerriGibson** [haozhu233/kableExtra#531] opened 2020-09-15 08:11 UTC
I'm having issues saving my table as an image. 

I tried save_kable but it didn't maintain all of the formatting (namely, some text that I need to be superscripted). 

I loaded the

When I tried as_image I got a bunch of error messages:

library("kableExtra")
library("magick")
library("webshot")
webshot::install_phantomjs()

 AP.BD.table<- AP.BD.SE %>% kbl(caption = "Table 1. Mean aeration porosity and bulk density for productive 
       and unproductive ACR and GLSA fields. The standard error of the mean is shown in brackets.", 
                                col.names = c('Field Quality', 'Depth', 'Time', 'Field Type',
                                              'n', '(%)   ',
                                              'n', '(Mg m$^{-3}$)'),align=rep('r', 4)) %>%
  kable_classic(full_width = F, html_font = "Times New Roman")%>%
   collapse_rows(columns = 1:4, valign = "top")%>%
   add_header_above(c(" " = 4, "Aeration Porosity" = 2, "Bulk Density" = 2))%>%
   as_image()

Error in setwd(dir) : cannot change working directory
In addition: Warning messages:
1: In file.create(file_temp_html) :
  cannot create file './/var/folders/m6/m3141f4n2t9clk55cvdgwq8c0000gn/T//RtmpXSvMPB/file64863758cf836486279fbdd8.html', reason 'No such file or directory'
2: In normalizePath(file_temp_html) :
  path[1]=".//var/folders/m6/m3141f4n2t9clk55cvdgwq8c0000gn/T//RtmpXSvMPB/file64863758cf836486279fbdd8.html": No such file or directory

**Comment by thegeologician** [comment] 2020-10-08 15:47
The same happens on my machine:

```
ttable<-data.table::data.table(a=c(1:3),b.column=c("one","banana","5.125432e-7"))
tkable<-knitr::kable(ttable,"html",escape=T)
kableExtra::save_kable(tkable,"C:/Users/mr/Documents/Data/scratch/test.png")
```

> Fehler in setwd(dir) : kann Arbeitsverzeichnis nicht wechseln
> Zusätzlich: Warnmeldungen:
> 1: In file.create(file_temp_html) :
>   kann Datei '.\C:/Users/mr/Documents/Data/scratch/test800ced742e6.html' nicht erzeugen. Grund 'Invalid argument'
> 2: In normalizePath(path.expand(path), winslash, mustWork) :
>   path[1]=".\C:/Users/mr/Documents/Data/scratch/test800ced742e6.html": The filename, directory name, or volume label syntax is incorrect

It looks like save_kable() (or a function somewhere in webshot) always tries to prepend the path with ".\", which 
- won't be correct for every use case (like when giving an absolute path)
- won't work on every platform (see above for classic mix of "\" and "/" in a Windows path...)

**Comment by thegeologician** [comment] 2020-10-08 15:50
Sorry, I just realised this is a duplicate of #499

**Comment by TerriGibson** [comment] 2020-10-08 18:11
Sorry about that, my bad! 

This isn't a solution per se, but in the end the simple work around for me was to copy and paste the table from the viewer into Microsoft Word, which is where I needed it.

**Comment by haozhu233** [comment] 2020-10-19 04:47
As I said in #499, this is an old bug #220. I tried to fix it in htmltools but they haven't accepted my pr yet. I'm closing this for now and we will use #499 to track this.

**Closed by haozhu233** 2020-10-19 04:47 UTC
