### ISSUE TITLE
Loading kableExtra breaks printing in skimr

### ISSUE THREAD

**Issue by elinw** [haozhu233/kableExtra#592] opened 2021-02-25 12:51 UTC
**Describe the bug**
We have a report and have confirmed that simply loading kableExtra in an rmarkdown file breaks the printing of skimr.  https://github.com/ropensci/skimr/issues/637

The issue occurs just by loading the library, it is not necessary to actually use any functions.  By default, skimr uses the knitr api for rendering when not in the console.  

I've confirmed that the column titles are not formatted correctly.
Additionally, in the console, when knitExtra is loaded, but not used and kable is used explicitly the results are changed to html.

If you can tell us how to fix this in our code that would be great, otherwise maybe there is a way that you can fix within kableExtra.

**To Reproduce**

````
---
title: "A reproducible example in rmarkdown"
output: 
  html_document:
    latex_engine: xelatex
---

```{r}
library(skimr)
library(knitr)
library(kableExtra) # this messes up the skim table
```

```{r}
skim(iris)
```
````

Example 2 in the console.
```
library(skimr)
library(knitr)
library(kableExtra)
skim(iris) %>% knitr::kable()
```

**Comment by haozhu233** [comment] 2021-02-25 14:14
Yeah, I made a dirty design choice in the early age of this package that if you load it it will change the default format of kable to html... That could be the root cause of all these issues. Anyway, I will look into that later today when I get time.

**Comment by elinw** [comment] 2021-03-20 23:00
@haozhu233  Did you ever get a chance to think about this?

**Comment by elinw** [comment] 2022-01-01 03:17
@haozhu233 Do you have any thoughts on this? Also dirty, but maybe we should force a change?

**Comment by francojc** [comment] 2022-12-26 16:07
A work around is to set an option to avoid kableExtra from generating HTML table output. 

```
options(kableExtra.auto_format = FALSE) # avoid kableextra from outputting HTML on kable tables
```

**Comment by vincentarelbundock** [comment] 2023-12-05 01:02
This should be fixed in the master development branch on Github. Please comment if you still run into the issue after installing from Github and restarting R.

**Closed by vincentarelbundock** 2023-12-05 01:02 UTC
