### ISSUE TITLE
hline_after in row_spec adds unwanted extra line for latex output

### ISSUE THREAD

**Issue by thmschk** [haozhu233/kableExtra#838] opened 2024-04-11 19:54 UTC
After an update of kableExtra to 1.4.0 , the following lines of code

```
kableExtra::kbl(head(mtcars), "latex", booktabs = T, linesep = "") %>%
row_spec(5, hline_after = T)
```
produce an extra line after midrule by two extra `\\`

```{latex}
\begin{tabular}[t]{lrrrrrrrrrrr}
\toprule
  & mpg & cyl & disp & hp & drat & wt & qsec & vs & am & gear & carb\\
\midrule
Mazda RX4 & 21.0 & 6 & 160 & 110 & 3.90 & 2.620 & 16.46 & 0 & 1 & 4 & 4\\
Mazda RX4 Wag & 21.0 & 6 & 160 & 110 & 3.90 & 2.875 & 17.02 & 0 & 1 & 4 & 4\\
Datsun 710 & 22.8 & 4 & 108 & 93 & 3.85 & 2.320 & 18.61 & 1 & 1 & 4 & 1\\
Hornet 4 Drive & 21.4 & 6 & 258 & 110 & 3.08 & 3.215 & 19.44 & 1 & 0 & 3 & 1\\
Hornet Sportabout & 18.7 & 8 & 360 & 175 & 3.15 & 3.440 & 17.02 & 0 & 0 & 3 & 2\\
\midrule\\
Valiant & 18.1 & 6 & 225 & 105 & 2.76 & 3.460 & 20.22 & 1 & 0 & 3 & 1\\
\bottomrule
\end{tabular}
```
I did not observe this behaviour before and I guess, it is a bug.

**Comment by dmurdoch** [comment] 2024-04-11 20:12
This is a duplicate of #833, which has been fixed.  You should use the devel version of `kableExtra` via

    remotes::install_github("haozhu233/kableExtra")

**Closed by dmurdoch** 2024-04-11 20:12 UTC

**Comment by dmurdoch** [comment] 2024-04-11 20:16
Sorry, #833 is also a duplicate; the original report was #815.
