### ISSUE TITLE
Compiling pdf in Rmarkdown with kableExtra full_width = T gives ! Dimension too large error with TeX Live 2021

### ISSUE THREAD

**Issue by martinschaffhauser** [haozhu233/kableExtra#625] opened 2021-06-09 11:07 UTC
Setting `full_width = T` in the kable function is giving the following error message when knitting the document with `pdfTeX Version 3.141592653-2.6-1.40.22 (TeX Live 2021)` installed:

```
! Dimension too large.
\LT@max@sel #1#2->{\ifdim #2=\wd \tw@ 
                                      #1\else \number \c@LT@chunks \fi }{\th...
l.218 \end{longtabu}
```
Having `pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020)` installed, the issue does not exist.

**Comment by samcarter** [comment] 2021-06-09 11:23
related to https://stackoverflow.com/q/67890758/2777074

**Comment by u-fischer** [comment] 2021-06-10 15:32
the tabu package is broken and unmaintained. It is recommended not to use it. See the readme here https://github.com/tabu-issues-for-future-maintainer/tabu

**Comment by wphampton** [comment] 2021-06-23 12:14
As it impacts kableExtra, does this suggest that `full_width` should not be used, or will not be provided in the future? I guess I'm unclear on what guidance is being given to the OP?

**Comment by krlmlr** [comment] 2021-10-06 14:35
Upstream issue: https://github.com/tabu-issues-for-future-maintainer/tabu/issues/27.

@u-fischer: What's a good alternative to tabu, one that supports full-width tables spanning multiple pages?

**Comment by ulyngs** [comment] 2022-06-09 15:24
Just ran into this issue when I tried to recompile my PhD thesis from a couple of years ago and the longtable functionality was broken.

Seems the [`tabularray`](https://ctan.org/pkg/tabularray) package is the new and maintained alternative which include longtable functionality -- is there an easy fix to make `kableExtra` use `tabulaarray` for longtables?

**Comment by eeholmes** [comment] 2023-03-19 00:53
It looks like this is closed, but the problem is still there. Any news of a workaround?

**Comment by tjbrailey** [comment] 2023-05-20 09:48
Bumping this, when `longtable = TRUE` and `full_width = TRUE`, I keep getting the error 

> ! Dimension too large. \LT@max@sel #1#2->{\ifdim #2=\wd \tw@ #1\else \number \c@LT@chunks \fi }{\th... l.376 \end{longtabu}

**Comment by vincentarelbundock** [comment] 2023-12-12 02:57
Thanks for the report. We know that `tabu` is broken beyond repair (and unmaintained). I will soon propose a solution (hopefully it gets accepted; not sure yet).

In any case, since there is no actionable information here, and no reproducible example, I will close this to clean up the issue tracker.

**Closed by vincentarelbundock** 2023-12-12 02:57 UTC
