### ISSUE TITLE
an error in repeat_header option when setting caption=NULL

### ISSUE THREAD

**Issue by Menger87** [haozhu233/kableExtra#384] opened 2019-05-18 16:53 UTC
@haozhu233, For repeat header in longtable, if I set caption=NULL, i.e.

kable(long_dt, "latex", longtable = T, booktabs = T, caption = NULL) %>%
add_header_above(c(" ", "Group 1" = 5, "Group 2" = 6)) %>%
kable_styling(latex_options = c("repeat_header"))

there is an error:
! Use of \@startpbox doesn't match its definition.
<inserted text> \@startpbox {
                             @{}l}
l.132 \multicolumn{10}{@{}l}{\textit{(continued)}}
                                                  \\ 

Is this a bug? This issue is happened after I update packages. It works before updated.

**Comment by haozhu233** [comment] 2020-08-20 00:34
Somehow I couldn't reproduce this bug. It's possible that it has been fixed in recent updates. At least with the latest version, it works fine.

**Closed by haozhu233** 2020-08-20 00:34 UTC
