### ISSUE TITLE
lazy loading failed for package ‘kableExtra’

### ISSUE THREAD

**Issue by muhammet-ozkaraca** [haozhu233/kableExtra#593] opened 2021-03-08 22:19 UTC
**Describe the bug**
Hi,
I am a relatively new user in R and I also post this comment on one of the previous issues but since it was closed, I wanted to post it again in a more detailed way and also so that people can see the solution, if any, to the problem. I think there is also a similar post recently in stackoverflow (https://stackoverflow.com/questions/66494953/not-able-to-install-umx-packaging-in-r-3-6-3/66537632#66537632) which leads me to think that the problem might arise due to some updates on CRAN, but anyway. So the think is I tried to upload kableExtra package in different ways like 
>install.packages('kableExtra') or 
>install.packages('kableExtra', dependencies = TRUE) or 
>install.packages('kableExtra', repos='https://cran.ma.imperial.ac.uk/') or 
>install.packages('kableExtra', repos='https://cloud.r-project.org/').

In each time, I get some kind of similar errors. To solve them, I tried to upload first of all those following packages and then "kableExtra",
>install.packages("hms") or 
>install.packages("svglite") 

but it did not work neither. Based on previous comments in the web, I also deleted svglite and said no to the warning (**Do you want to install from sources the package which needs compilation?**) but it did not work as well. I am always getting a similar error to this;
> install.packages('kableExtra', repos='https://cran.ma.imperial.ac.uk/')
also installing the dependency ‘svglite’

  There are binary versions available but the source versions are later:
            binary source needs_compilation
svglite    1.2.3.2  2.0.0              TRUE
kableExtra   1.3.2  1.3.4             FALSE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) no
URL 'https://cran.ma.imperial.ac.uk/bin/macosx/el-capitan/contrib/3.6/svglite_1.2.3.2.tgz' deneniyor
Content type 'application/x-gzip' length 479985 bytes (468 KB)
==================================================
downloaded 468 KB

The downloaded binary packages are in
	/var/folders/v5/x84l_nj94zj0jvjhlv50l1740000gn/T//RtmpmKYQVM/downloaded_packages
installing the source package ‘kableExtra’

URL 'https://cran.ma.imperial.ac.uk/src/contrib/kableExtra_1.3.4.tar.gz' deneniyor
Content type 'application/x-gzip' length 1646490 bytes (1.6 MB)
==================================================
downloaded 1.6 MB

* installing *source* package ‘kableExtra’ ...
** package ‘kableExtra’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  paylaşılan nesne '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so' yüklenemedi:
 dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so
  Reason: image not found
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Çalıştırma durduruldu
ERROR: lazy loading failed for package ‘kableExtra’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/kableExtra’
Warning in install.packages :
  installation of package ‘kableExtra’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/v5/x84l_nj94zj0jvjhlv50l1740000gn/T/RtmpmKYQVM/downloaded_packages’

**Comment by rhurlin** [comment] 2021-03-09 07:25
>     * dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
>       Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so
>       Reason: image not found
>       Calls:  ... asNamespace -> loadNamespace -> library.dynam -> dyn.load

Hi muhammet-ozkaraca,

The quoted part of the messages of your last installation example seems to complain about a missing library from **package systemfonts**. Did you try to reinstall or update R package systemfonts before installing kableExtra?

`install.packages('systemfonts', dependencies = TRUE)`

BTW, your version of R itself is one year old. Perhaps this is the time to update to v4.0.4?

**Comment by rhurlin** [comment] 2021-03-09 11:00
Nice to hear that it works for you :dagger: 

(Hint) If the issue is now resolved for you, you should consider closing the issue.

**Closed** 2021-03-10 08:57 UTC
