### ISSUE TITLE
kable_styling not respecting html tags in cells

### ISSUE THREAD

**Issue by norcalbiostat** [haozhu233/kableExtra#24] opened 2017-07-19 23:52 UTC
After applying kable_styling html tags inside cells are not being respected. 

E.g. this is one of my cell entries

`&bull; Review ANOVA vocabulary <br>  &bull; Read up on the [final project instructions](../Projects/ProjectPage.html).`

Neither the bullet points, nor the line break tags are rending. The link however works just fine.

**Comment by norcalbiostat** [comment] 2017-07-20 00:35
Never mind - it's a bootstrap theme problem. Problem exists w/o kable_styling.

**Comment by haozhu233** [comment] 2017-07-20 01:54
Hi, @norcalbiostat, just in case you haven't figure it out, to display raw HTML in your cell, use the `escape` option in `kable`.

`kable(dt, "html", escape = F) %>% kable_styling()`

**Comment by norcalbiostat** [comment] 2017-07-20 21:30
Unfortunately that doesn't work either.

And i'm not sure it's a theme problem. I just tried using blank theme/new RMD document and the <br> isn't being rendered by itself, and adding `escape=F` throws an error about opening and ending tab mismatch between br and td. 

I've attached the RMD file and the Excel file that contains the table that i'm importing and kable()'ing

[test tag error.zip](https://github.com/haozhu233/kableExtra/files/1163740/test.tag.error.zip)

**Comment by haozhu233** [comment] 2017-07-20 21:48
Hmm, `escape` should work in most cases... Are you trying to make some bullet point listing? How about using the following format.

```
<ul><li>Review ANOVA vocabulary</li><li>Read up on the [final project instructions](../Projects/ProjectPage.html).</li></ul>
```
It is more formal than creating bullet points by yourself. You still need to set `escape` to `FALSE` in this case. 

Or an alternative approach is to put each point in a single row and use `collapse_rows` function.

**Comment by norcalbiostat** [comment] 2017-07-20 21:56
Yep, bulleted list. Ok, the formal list structure works, but my word the spacing between the bullets and words is HUGE. Next thing for me to google how to do. 

I've thought about and played around with the collapse_rows function, but it makes the cell shading look weird, and without being able to get the cell row borders to show it's more difficult to tell between days.  i'm also having issues with the cell borders not showing up, even with adding a custom css, but i'm pretty much giving up on that one. The contents of this table get quite large, so it's easier to keep one day per row. Thanks for your help!

**Comment by haozhu233** [comment] 2017-07-20 22:01
lol I'm also having troubles with cell shading when I'm using `collapse_rows` Hahaha. I don't have a solution for it either at this moment. 

To solve the spacing problem, you need to left-align your contents in that column. I updated my comments above with a file. You can take a look there.

**Comment by vrybkin** [comment] 2017-07-21 19:03
Hi,

Thank you for developing this package. I am really excited to begin using kableExtra as it has many features that I've been looking for. However, I'm getting the same error on a really simple example below. It seems that the <br> tag is never closed, but kable() renders this without a problem. Is there any solution to this problem?

```
---
title: "Test kableExtra"
output: 
  html_document:
    theme: flatly
---
  

```{r}
library(kable)
library(kableExtra)

D = data.frame( Summary = c("97<br>84%", "23.1&plusmn;2.3") )
rownames(D) = c("var1", "var2")

kable(D, format = "html", align = "c", escape = F) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "responsive"), full_width = F)
```

Error message:
```
Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  : 
  Opening and ending tag mismatch: br line 11 and td [76]
Calls: <Anonymous> ... read_xml.character -> read_xml.raw -> doc_parse_raw -> .Call
Execution halted
```

Thank you for your time!

**Comment by haozhu233** [comment] 2017-07-21 19:12
I'm reopening this issue as xml2 does seem to fail really bad on this part.

**Comment by haozhu233** [comment] 2017-07-21 19:38
@vrybkin Okay, I've figured it out. It is completely a XML issue. 

To solve these kind of problem, you can follow the following guidance.  
1. For any self-closing HTML tags like `<br>`, use their closed version `<br />` or `<br/>`. As said in [W3School](https://www.w3schools.com/tags/tag_br.asp):
> In XHTML, the `<br>` tag must be properly closed, like this: `<br />`.

2. For special symbols like `&plusmn;`, don't use its HTML entity. Instead, you should use its ASCII code like `&#177;`. You can use this table: http://www.econlib.org/library/asciicodes.html for any necessary conversion.

**Comment by vrybkin** [comment] 2017-07-21 19:53
@haozhu233 Thanks for your prompt reply! It makes sense. I've got a bunch of legacy code with unclosed HTML tags. Do you think it's likely that you would ever support unclosed tags, such as the way datatable and kable do?

**Comment by haozhu233** [comment] 2017-07-24 19:17
@vrybkin Okay, I just made some changes to the entire package so all the functions can digest HTML entities like `&plusmn;` and unclosed tags like `<br>`.

**Comment by vrybkin** [comment] 2017-07-24 20:54
@haozhu233 Thank you so much, highlight to my day :) This works really well and my tables now look much much better than they did before. One little thing that I'm still seeing in that example is that "&plusmn;" gets converted to "Â±".

**Comment by haozhu233** [comment] 2017-07-24 21:40
This bug was created by a bug in `base::readLines()`(😲😲😲) under Windows. It won't happen if the machine is a Mac. I switched that function to `readr::read_file` and fixed it in the latest dev version. Thanks for pointing it out! This kind of system difference is hard to notice.

**Comment by vrybkin** [comment] 2017-07-24 22:56
@haozhu233 Thank you! I also noticed that `"&emsp;"` does not map to an indent. For example, I used: `"Gender<br> &emsp;Female<br> &emsp;Male"` as a rowname to a table and it is no longer indented. Is this another issue with `reader::read_file`?

Thanks again!

**Comment by haozhu233** [comment] 2017-07-25 03:28
@vrybkin I can't reproduce the bug you mentioned. Did you set `align = "l"` for that column?

**Comment by vrybkin** [comment] 2017-07-25 13:14
@haozhu233 Sorry, here's an example, I hope this makes my issue clear. I have a data.frame with the `rownames()` being: `c("Age", "Gender<br> &emsp;Female<br> &emsp;Male", "Disease Duration"                     , "Lab 1 (mmol/L)")`. Note that in this case, the "Gender" row in the table is actually composed of three separate lines.

Using just `kable()`, these rownames render with the `&emsp;` character forcing an indent after the newline character `<br>`.

Using `kable()`:
![image](https://user-images.githubusercontent.com/18724720/28573580-1216026c-7119-11e7-8807-7932b74c4e41.png)

Using `kable() %>% kable_styling`, the indent character is not read:
![image](https://user-images.githubusercontent.com/18724720/28573711-7e784118-7119-11e7-80ac-be99e1e3bbec.png)

Hope this helps!

**Comment by haozhu233** [comment] 2017-07-25 16:55
Hmm, I tested it on Windows/Mac and they both work... Therefore, I'm going to treat it as solved and close this issue. @vrybkin Let discuss via email for this individual case.

**Closed by haozhu233** 2017-07-25 16:55 UTC
